name: OpenActive.Server.NET.Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout OpenActive.Server.NET
      uses: actions/checkout@v2
    - name: Setup .NET Core 2.1.808
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.808
    - name: Setup Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install OpenActive.Server.NET dependencies
      run: dotnet restore ./
    - name: Run OpenActive.Server.NET Tests
      run: dotnet test ./OpenActive.Server.NET.Tests/OpenActive.Server.NET.Tests.csproj --configuration Release --no-restore --verbosity normal
